---
- name: Install required libs
  ansible.builtin.apt:
    name:
      - curl
      - git
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - openjdk-11-jdk-headless
      - firewalld
      - ansible
    state: present
    update_cache: yes
